[application]
name = "Components Demo"
default_platform = "web"
asset_dir = "assets"

[web.app]
title = "组件与 Props"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource.dev]
style = ["assets/main.css"]
