[application]
name = "Platform Demo"
default_platform = "web"
asset_dir = "assets"

[web.app]
title = "平台适配"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource.dev]
style = ["assets/main.css"]
